### ISSUE TITLE
第9单元中， file=sys.err 引发语法错误

### ISSUE THREAD

**Issue by ziyuanjun** [zhanwen/PythonDataScience#2]
语句提示存在语法错误：
```python
print("Could not open %s" % doc, file=sys.err)
```

目前修改为：
```python
print("Could not open %s" % doc,  sys.err)
```
参考：
https://github.com/ziyuanjun/PythonDataScience/blob/master/chapter2/u9_urlopen.py

**Comment by zhanwen** [comment]
这个是因为少导入了，加上`import sys`,就可以了。

**Comment by ziyuanjun** [comment]
> 加上`import sys`,就可以了

并不是这样吧 ^-^

**Comment by zhanwen** [comment]
在我这是可以的，你用的哪个版本的python？

**Comment by ziyuanjun** [comment]
哦，可能是版本的问题，回头我再换其他版本试试。我的是 3.5.2
